### ISSUE TITLE
Building saf_mkl_custom.dll

### ISSUE THREAD

**Issue by tonetechnician** [leomccormack/Spatial_Audio_Framework#1]
Hey there! 

Thank you and your team so much for this project. It really is so great to have this framework in place.

I've been wanting to incorporate this framework into my node environment using N-API wrapping for the SAF functions. I build these wrappers using the [node-gyp](https://github.com/nodejs/node-gyp) tool. So far, I'm able to get the project to build, but am running into errors when I try run the project with the saf_mkl_custom.dll that came with the SPARTA plugins - you can find further info on my issue here [#1834](https://github.com/nodejs/help/issues/1834). As shown in this issue, when I include the saf_mkl_custom.dll in my node extension, I see that there are some functions in the .dll that are missing, or not referenced correctly and the module is unable to run. The dependency walker confirms this. 

![image](https://user-images.githubusercontent.com/13471797/54739151-c2c46b80-4bbf-11e9-97b1-71033d3a6a7d.png)

I'm still trying to figure out if this is a node-gyp issue or an issue with the saf_mkl_custom.dll. 

I'm using windows 10. I have installed intel's MKL library and am using Visual Studio 2017 nmake for the .dll compilation.

I've since decided that I should try build the .dll from scratch to see if I can find more information. I've tried to run the command mentioned in the readme. I run this command from the dependencies/win64 directory.

```.cmd
nmake intel64 interface=lp64 threading=sequential name=saf_mkl_custom export=saf_mkl_list
```

However, I get thrown this error from nmake 

```.cmd
Microsoft (R) Program Maintenance Utility Version 14.15.26730.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1073: don't know how to make 'intel64'
Stop.
```

Might you have any idea why this error would be thrown? 

Any help would be greatly appreciated :)

**Comment by tonetechnician** [comment]
Interestingly, I see that [this commit](https://github.com/leomccormack/Spatial_Audio_Framework/commit/7664dd4c4b3e70819ec99129d89b24da621d7a6a) includes one of the functions that dependency walkers shows is missing in the .dll cgesvd_. 

I've pull the latest version of the code but am still unable to build the saf_mkl_custom.dll. Did you update the SPARTA plguins with the new saf_mkl_custom.dll?

**Comment by leomccormack** [comment]
Hey!
There will be a new SPARTA release (hopefully) later today/tomorrow, which will include the latest saf_mkl_custom.dll. And apologies, the instructions were pretty vague, I just edited the readme, which might help, if you need it urgently.
Cheers!

**Comment by tonetechnician** [comment]
Thanks so much for the fast reply :) look forward to trying it out. Hopefully this fixes the library linking

**Comment by tonetechnician** [comment]
Perfect, this fixed it on my end. Am now able to import the framework into my node project :D Hope to have a .node addon version of the framework for javascript over the next few weeks. Hope this makes you as excited as it makes me! 

Thanks for writing such great code and open sourcing this library. It is really a master piece of spatial audio code.
