### ISSUE TITLE
example with audio file

### ISSUE THREAD

**Issue by HuongNV96** [leomccormack/Spatial_Audio_Framework#16]
Hi all,
Can you share for me a example , which process in audio file ( as mp3 , wav, raw)?
 Best Regards,
HuongNV

**Comment by leomccormack** [comment]
Hi, we don't currently have a standalone example of the framework in action, with some wavfile reader/writer; perhaps this is something to look into in the future. 

However, if you wish to process audio files with existing code, you could use the SPARTA VST plugins: https://github.com/leomccormack/SPARTA inside of e.g. REAPER. (Note that SPARTA is basically the VST wrapper + GUI for the SAF examples)

Hope this helps : )

**Comment by aidanasingh** [comment]
It is a bit unclear how to use the framework outside of a CMake workflow, which I am unfamiliar with. I want to unit test bessel_jn, would I be able to call this function in a file that I compile with g++?  I have Intel MKL LP64 installed.
