### ISSUE TITLE
Build instructions do not work

### ISSUE THREAD

**Issue by d01010101** [leomccormack/Spatial_Audio_Framework#19]
I use plain Ubuntu.

$ cmake -S . -B build
CMake Error: The source directory "/home/df/Spatial_Audio_Framework-master/build" does not exist.
$ cmake --version
cmake version 3.10.2

**Comment by leomccormack** [comment]
Hi! the error is referring to the directory "build" not being found. I believe newer versions of CMake will do this automatically if the build directory does not exist; i.e. it will do:
$ mkdir build
$ cmake -S . -B build

But perhaps changing the instructions to the following more "default" approach, might be an idea to avoid such confusion in future
$ mkdir build && cd build
$ cmake ..

**Comment by d01010101** [comment]
I tried this before submitting this error. It complained about some file missing in `build`. For cmake, `build` is the source directory for whatever reason, as seen in the error message. I will try with a newer version, if it is already available in Ubuntu.
