### ISSUE TITLE
Cython wrappers for Python

### ISSUE THREAD

**Issue by silent-code** [leomccormack/Spatial_Audio_Framework#24]
Hi, what is the current status of the python wrappers for the SAF? Are they available for public distro yet? Thanks in advance!

Regards,
Tim

**Comment by leomccormack** [comment]
Hi, apologies for the late reply!

This was more of experiment, but if people are interested and willing to contribute, we will keep at it : )

Here's the repo, which has wrappers for SH functions, VBAP, and the alias-free STFT implementations from SAF. 
https://github.com/chris-hld/SAFpy
