### ISSUE TITLE
install-safmkl.sh script fails to compile the linux libsaf_mkl_custom.so library

### ISSUE THREAD

**Issue by marclava** [leomccormack/Spatial_Audio_Framework#27]
[install-safmkl-linux.patch.gz](https://github.com/leomccormack/Spatial_Audio_Framework/files/6125517/install-safmkl-linux.patch.gz)

## Description

The install-safmkl.sh script fails to compile the linux libsaf_mkl_custom.so library. Included patch fix the issue on my system.

## Environment

1. OS: Ubuntu 20.04
2. Compiler: GCC
3. SAF performance library being used: SAF_USE_INTEL_MKL

## Additional information

I use the intel-mkl-core-rt-2020.4-304 ubuntu package.

**Comment by leomccormack** [comment]
Thanks for letting me know!
It would be nice if Intel could decide and then stick to a consistent folder structure across releases. :S 

So it seems the script should now check for both:
iomp5_dir="/opt/intel/compilers_and_libraries/linux/lib/intel64"
iomp5_dir="/opt/intel/compilers_and_libraries/linux/compiler/lib/intel64_lin"

And I've recently been made aware that the mkl_core library is now in a different path, with Intel MKL now being wrapped within the new Intel OneAPI, so there are more potential default folders to scan for that library as well. 

I suppose a robust solution would be for the script to allow the user to manually specify the file paths, if none of the (numerous) default locations can be found.

**Comment by marclava** [comment]
Maybe the script could search for specific files in order to find the path, using the find command.

**Comment by leomccormack** [comment]
The problem is that e.g. Matlab and Anaconda both package the mkl_core library in their installations, which can be of different versions and configurations. So for those with Matlab and/or python installed (probably others aswell), it could find multiple libraries of the same name, which are all bit different and may not jell well with the include headers : S

**Comment by leomccormack** [comment]
The new updated sh script should now work. By default it will use the new "oneapi" directory path, but it also supports passing the location of the mkl/tools/builder folder, e.g. for the old or custom installation directories. But please let me know if there's still an issue.
