### ISSUE TITLE
bessel_jn does not return expected values

### ISSUE THREAD

**Issue by aidanasingh** [leomccormack/Spatial_Audio_Framework#47]
## Description

The function [`bessel_jn`](https://github.com/leomccormack/Spatial_Audio_Framework/blob/377fd0d0115377aa984917d7cca0bd3e805066e0/framework/modules/saf_utilities/saf_utility_bessel.h#L136-L162) (spherical) is described to compute the bessel function of the first kind and its derivative. I would therefore expect the function [`scipy.special.spherical_jn`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.spherical_jn.html) to return the same values. I have been editing values in `test__sh_module.c` and added print statements to `bessel_jn` to see the behavior of `bessel_jn`, and noticed that the values returned by `bessel_jn` do not match the theory. One discrepancy is that `bessel_jn` always outputs a value of `j_n[i]=1` for an input of `z[i]=0` even for orders above 1, when bessel functions above order 1 have a value a value of `j_n[i]=0` when `z[i]=0`. I'm wondering why there is an [if-statement](https://github.com/leomccormack/Spatial_Audio_Framework/blob/377fd0d0115377aa984917d7cca0bd3e805066e0/framework/modules/saf_utilities/saf_utility_bessel.c#L524) setting `j_n` to `1` at `z` of `0` for all orders, and if bessel_jn is intended to match the theory otherwise.

## Environment

1. OS:                                                          MacOSX 11.6
2. Compiler:                                               Making and executing the saf_test executable
3. SAF performance library being used: SAF_USE_INTEL_MKL
4. Any optional SAF flags enabled:         N/A
5. Other environment details:                  CMake

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add print statements for the arguments of `bessel_jn` to the beginning of `bessel_jn`, and of the outputs at the end of `bessel_jn`
2. In the function `test__sphModalCoeffs` in the file `test__sh_module.c`, set kr to an array of values from 0 to 9 (step of 1) after line [709](https://github.com/leomccormack/Spatial_Audio_Framework/blob/377fd0d0115377aa984917d7cca0bd3e805066e0/test/src/test__sh_module.c#L709)
3. Insert this call of `sphModalCoeffs` at 714:
`sphModalCoeffs(2, kr, 10, ARRAY_CONSTRUCTION_OPEN_DIRECTIONAL, 1.0, FLATTEN2D(b_N_card));`
(can edit the first argument to change the order)

## Expected Output

![Screen Shot 2022-03-09 at 11 00 37 AM](https://user-images.githubusercontent.com/95709291/157479860-90a115b7-c13b-4494-a6db-6ea60cb68e4e.png)

## Actual Output

![Screen Shot 2022-03-09 at 11 01 37 AM](https://user-images.githubusercontent.com/95709291/157480039-391d7db6-4f50-4b3a-920d-4e9f0f5c0871.png)

Notice that besides the issue of `j_n[0]` being 1, none of the values match anyways. Curiously, `jn[2]` (scipy) is equivalent to `j_n[1]` (saf).

**Comment by leomccormack** [comment]
Ah yes. I knew this day would come.

In SAF, the bessel_jn() function actually evaluates **all** orders up to the specified order N. 
i.e. 0,1,...,N

If you do, e.g.:
```
    int maxN;
    double z[10] = {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0};
    double j_n[10][3];

    bessel_jn(2, z, 10, &maxN, j_n, NULL);
```

Then the final column are the values you are looking for:

```
Printing description of j_n:
(double [10][3]) j_n = {
  [0] = ([0] = 1, [1] = 0, [2] = 0)
  [1] = ([0] = 0.8414709848078965, [1] = 0.3011686789397568, [2] = 0.062035052011373874)
  [2] = ([0] = 0.45464871341284085, [1] = 0.43539777497999155, [2] = 0.19844794905714652)
  [3] = ([0] = 0.047040002686622465, [1] = 0.34567749976235596, [2] = 0.2986374970757335)
  [4] = ([0] = -0.18920062382698205, [1] = 0.11611074925915747, [2] = 0.27628368577135015)
  [5] = ([0] = -0.1917848549326277, [1] = -0.095089408079170781, [2] = 0.13473121008512523)
  [6] = ([0] = -0.046569249699820958, [1] = -0.16778992272503115, [2] = -0.037325711662694619)
  [7] = ([0] = 0.093855228388398409, [1] = -0.094292432279272309, [2] = -0.13426627079380082)
  [8] = ([0] = 0.12366978082792272, [1] = 0.033646226829567055, [2] = -0.11105244576683508)
  [9] = ([0] = 0.045790942804639571, [1] = 0.10632457829881295, [2] = -0.010349416705035258)
```

**Comment by leomccormack** [comment]
The main reason for this is that currently all of the SAF functions that require these bessel values need them from 0..N anyway.

Although. perhaps, yes... The `bessel_jn()` function should be changed to return only the requested N, and a new `bessel_jn_ALL()` can take on the existing 0..N functionality.

**Comment by leomccormack** [comment]
Actually, I've now done this. See latest commit on the develop branch : )

**Comment by aidanasingh** [comment]
Thank you! This makes sense now, and when properly printing the output of `bessel_jn` it now matches the scipy function for all orders up to the order specified. Are there any reasons to believe that `scipy.special.spherical_jn` won't function like `bessel_jn` when calculating the modal coefficients for the spherical harmonic transform? Ultimately this is why I'm curious about the `bessel_jn` function.

Interestingly the scipy function takes complex numbers as arguments, which `bessel_jn` doesn't. Would there be any utility in having `bessel_jn` take complex inputs?
