### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by hectorC** [leomccormack/Spatial_Audio_Framework#52]
When trying to execute the script install-safmkl.bat on Windows 11 (Visual Studio 2022) it fails with the following error:

`NMAKE : fatal error U1073: don't know how to make 'intel64'`

I built SAF without any problems by doing the alternate option of using the stock MKL libraries from the OneAPI, but I was wondering what could be causing this issue?

**Comment by hectorC** [comment]
Strangely, if I build the MKL library by manually entering the corresponding build commands from the bat file, then it works.

**Comment by leomccormack** [comment]
It sounds like the issue was resolved. However, please reopen the issue, if there is another related problem.
